Faça como eu fiz: criando e manipulando listas, tuplas e dicionários

Crie uma lista com seus filmes favoritos;

Crie uma tupla com as datas que você assistiu esses filmes;

A partir da lista, crie um dicionário onde a chave é o nome do filme e depois adicione a data que você assistiu o filme como valor.

In [1]:
filmes = ['O poderoso chefão', 'Um sonho de liberdade', 'Donnie Darko']
datas = '01/08/2000', '25/06/2019', '30/04/2020'

filmes_dict = {filme:data for filme, data in zip(filmes, datas)}

print(filmes)
print(datas)
print(filmes_dict)

['O poderoso chefão', 'Um sonho de liberdade', 'Donnie Darko']
('01/08/2000', '25/06/2019', '30/04/2020')
{'O poderoso chefão': '01/08/2000', 'Um sonho de liberdade': '25/06/2019', 'Donnie Darko': '30/04/2020'}

In [2]:
for chave, valor in filmes_dict.items():
    print(f'{chave}: {valor}')

O poderoso chefão: 01/08/2000
Um sonho de liberdade: 25/06/2019
Donnie Darko: 30/04/2020

1. Crie um programa que grave em um arquivo alunos.csv uma lista de alunos e suas notas.
2. Leia o arquivo alunos.csv e imprima apenas os alunos com nota maior ou igual a 7.0.

In [4]:
import csv

alunos = input('Digite os nomes dos alunos separados por vírgula: ').split(',')
notas = input('Digite as notas correspondentes separadas por vírgula: ').split(',')

alunos = [aluno.strip() for aluno in alunos]
notas = [float(nota.strip()) for nota in notas]

with open ('alunos.csv', 'w', newline = '', encoding = 'utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['Aluno', 'Nota'])
    for aluno, nota in zip(alunos, notas):
        writer.writerow([aluno, nota])

with open('alunos.csv', 'r', newline = '', encoding = 'utf-8') as f:
    reader = csv.reader(f)
    for i, linha in enumerate(reader):
        if i == 0:
            print(linha)
        else:
            if float(linha[1]) >= 7:
                print(linha)

['Aluno', 'Nota']
['joão', '10.0']
['maria', '10.0']

## Consultas - banco de dados

##### Para ver como criar, escrever, ler e atualizar, ver arquivos create, write, read e update

In [2]:
import sqlite3

conn = sqlite3.connect('school.db')

cursor = conn.cursor()

cursor.execute(
    '''
        SELECT * FROM estudantes
        WHERE id = 1
    '''
)

conn.commit()

estudante = cursor.fetchall()
print(estudante)

conn.close()

[(1, 'Joana', 16)]

In [2]:
import sqlite3

conn = sqlite3.connect('school.db')

cursor = conn.cursor()

cursor.execute(
    '''
        SELECT estudantes.nome, disciplinas.nome_disciplina 
        FROM disciplinas 
        JOIN estudantes
            ON disciplinas.estudante_id = estudantes.id
    '''
)

conn.commit()

consulta = cursor.fetchall()
print(consulta)

conn.close()

[('Joana', 'Matemática'), ('Leandro', 'Física')]

Desafio: Interagindo com banco de dados

A rede de hotelaria HotelPlus te contratou para criar um pequeno sistema de cadastro de usuários. A priori você precisa criar uma tabela chamada usuarios com os seguintes campos:

id (inteiro, chave primária)

nome (texto)

email (texto)

Para testar o seu banco de dados, adicione 2 usuários na tabela usuarios e depois consulte todos os registros.

In [3]:
import sqlite3

conn = sqlite3.connect('hotelplus.db')

cursor = conn.cursor()

cursor.execute(
    '''
        CREATE TABLE IF NOT EXISTS usuarios(
            id INTEGER PRIMARY KEY,
            nome TEXT,
            email TEXT
        )
    '''
)

conn.commit()

conn.close()

In [4]:
import sqlite3

conn = sqlite3.connect('hotelplus.db')

cursor = conn.cursor()

cursor.execute(
    '''
        INSERT INTO usuarios(nome, email)
        VALUES(?, ?)
    ''',
    ('Júnior', 'juniorteste@gmail.com')
)

conn.commit()

conn.close()

In [6]:
import sqlite3

conn = sqlite3.connect('hotelplus.db')

cursor = conn.cursor()

usuarios = [
    ('João', 'joãozinho@gmail.com'),
    ('Maria', 'mariazinha@gmail.com'),
    ('José', 'zezinho@gmail.com')
]

cursor.executemany(
    '''
        INSERT INTO usuarios(nome, email)
        VALUES(?, ?)
    ''',
    usuarios
)

conn.commit()

conn.close()

In [7]:
import sqlite3

conn = sqlite3.connect('hotelplus.db')

cursor = conn.cursor()

cursor.execute(
    '''
        SELECT *
        FROM usuarios
    '''
)

conn.commit()

consulta = cursor.fetchall()

for linha in consulta:
    print(linha)

conn.close()

(1, 'Júnior', 'juniorteste@gmail.com')
(2, 'João', 'joãozinho@gmail.com')
(3, 'Maria', 'mariazinha@gmail.com')
(4, 'José', 'zezinho@gmail.com')

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('hotelplus.db')

cursor = conn.cursor()

cursor.execute(
    '''
        SELECT *
        FROM usuarios
    '''
)

conn.commit()

consulta = cursor.fetchall()

df = pd.DataFrame(consulta, columns = ['id', 'nome', 'email'])
display(df)

conn.close()

   id    nome                  email
0   1  Júnior  juniorteste@gmail.com
1   2    João    joãozinho@gmail.com
2   3   Maria   mariazinha@gmail.com
3   4    José      zezinho@gmail.com

A Loja TechMais está informatizando seu controle de estoque
O gerente quer um sistema simples em Python que registre e consulte produtos no banco de dados loja.db.

Se conecta ao banco loja.db;

Crie uma tabela produtos com os campos id, nome, preco;

Insira 3 produtos diferentes;

Liste todos os produtos cadastrados.

Dica: use funções como criar_produto(nome, preco) e listar_produtos().

In [1]:
import sqlite3
import pandas as pd

def conectar():
    conn = sqlite3.connect('loja.db')
    cursor = conn.cursor()
    return conn, cursor

def desconectar(conn):
    conn.commit()
    conn.close()    

def criar_tabela_produtos():
    conn, cursor = conectar()
    cursor.execute(
        '''
            CREATE TABLE IF NOT EXISTS produtos(
                id INTEGER PRIMARY KEY,
                nome TEXT,
                preco FLOAT
            )
        '''
    )
    desconectar(conn)

def criar_produtos(lista_produtos):
    conn, cursor = conectar()
    cursor.executemany(
        '''
            INSERT INTO produtos(nome, preco)
            VALUES(?, ?)
        ''',
        lista_produtos
    )
    desconectar(conn)

def listar_produtos():
    conn, cursor = conectar()
    cursor.execute(
        '''
            SELECT * FROM produtos
        '''
    )
    produtos = cursor.fetchall()
    df = pd.DataFrame(produtos, columns = ['id', 'nome', 'preco'])
    desconectar(conn)
    return df

def main():
    conectar()
    criar_tabela_produtos()
    lista_produtos = [
        ('PS5', 3599.99),
        ('Macbook', 19999.99),
        ('Apple Watch', 6899.99)
    ]
    criar_produtos(lista_produtos)
    df = listar_produtos()
    display(df)

if __name__ == '__main__':
    main()

   id         nome     preco
0   1          PS5   3599.99
1   2      Macbook  19999.99
2   3  Apple Watch   6899.99